// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcRquestContext.proto

package test.chao.pa.netty;

public final class RootProtoGen {
  private RootProtoGen() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TypeValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TypeValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>bytes value = 2;</code>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code TypeValue}
   */
  public  static final class TypeValue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TypeValue)
      TypeValueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TypeValue.newBuilder() to construct.
    private TypeValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TypeValue() {
      type_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TypeValue();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TypeValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 18: {

              value_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.chao.pa.netty.RootProtoGen.internal_static_TypeValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.chao.pa.netty.RootProtoGen.internal_static_TypeValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.chao.pa.netty.RootProtoGen.TypeValue.class, test.chao.pa.netty.RootProtoGen.TypeValue.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>bytes value = 2;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (!value_.isEmpty()) {
        output.writeBytes(2, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.chao.pa.netty.RootProtoGen.TypeValue)) {
        return super.equals(obj);
      }
      test.chao.pa.netty.RootProtoGen.TypeValue other = (test.chao.pa.netty.RootProtoGen.TypeValue) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.chao.pa.netty.RootProtoGen.TypeValue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.chao.pa.netty.RootProtoGen.TypeValue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.chao.pa.netty.RootProtoGen.TypeValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.chao.pa.netty.RootProtoGen.TypeValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.chao.pa.netty.RootProtoGen.TypeValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.chao.pa.netty.RootProtoGen.TypeValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.chao.pa.netty.RootProtoGen.TypeValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.chao.pa.netty.RootProtoGen.TypeValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.chao.pa.netty.RootProtoGen.TypeValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.chao.pa.netty.RootProtoGen.TypeValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.chao.pa.netty.RootProtoGen.TypeValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.chao.pa.netty.RootProtoGen.TypeValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.chao.pa.netty.RootProtoGen.TypeValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TypeValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TypeValue)
        test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.chao.pa.netty.RootProtoGen.internal_static_TypeValue_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.chao.pa.netty.RootProtoGen.internal_static_TypeValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.chao.pa.netty.RootProtoGen.TypeValue.class, test.chao.pa.netty.RootProtoGen.TypeValue.Builder.class);
      }

      // Construct using test.chao.pa.netty.RootProtoGen.TypeValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = "";

        value_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.chao.pa.netty.RootProtoGen.internal_static_TypeValue_descriptor;
      }

      @java.lang.Override
      public test.chao.pa.netty.RootProtoGen.TypeValue getDefaultInstanceForType() {
        return test.chao.pa.netty.RootProtoGen.TypeValue.getDefaultInstance();
      }

      @java.lang.Override
      public test.chao.pa.netty.RootProtoGen.TypeValue build() {
        test.chao.pa.netty.RootProtoGen.TypeValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.chao.pa.netty.RootProtoGen.TypeValue buildPartial() {
        test.chao.pa.netty.RootProtoGen.TypeValue result = new test.chao.pa.netty.RootProtoGen.TypeValue(this);
        result.type_ = type_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.chao.pa.netty.RootProtoGen.TypeValue) {
          return mergeFrom((test.chao.pa.netty.RootProtoGen.TypeValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.chao.pa.netty.RootProtoGen.TypeValue other) {
        if (other == test.chao.pa.netty.RootProtoGen.TypeValue.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.chao.pa.netty.RootProtoGen.TypeValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.chao.pa.netty.RootProtoGen.TypeValue) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes value = 2;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>bytes value = 2;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TypeValue)
    }

    // @@protoc_insertion_point(class_scope:TypeValue)
    private static final test.chao.pa.netty.RootProtoGen.TypeValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.chao.pa.netty.RootProtoGen.TypeValue();
    }

    public static test.chao.pa.netty.RootProtoGen.TypeValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TypeValue>
        PARSER = new com.google.protobuf.AbstractParser<TypeValue>() {
      @java.lang.Override
      public TypeValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TypeValue(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TypeValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TypeValue> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.chao.pa.netty.RootProtoGen.TypeValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestContextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestContext)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 seq = 1;</code>
     */
    int getSeq();

    /**
     * <code>string clz_name = 2;</code>
     */
    java.lang.String getClzName();
    /**
     * <code>string clz_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getClzNameBytes();

    /**
     * <code>string method_name = 3;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>string method_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>repeated .TypeValue method_param = 4;</code>
     */
    java.util.List<test.chao.pa.netty.RootProtoGen.TypeValue> 
        getMethodParamList();
    /**
     * <code>repeated .TypeValue method_param = 4;</code>
     */
    test.chao.pa.netty.RootProtoGen.TypeValue getMethodParam(int index);
    /**
     * <code>repeated .TypeValue method_param = 4;</code>
     */
    int getMethodParamCount();
    /**
     * <code>repeated .TypeValue method_param = 4;</code>
     */
    java.util.List<? extends test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder> 
        getMethodParamOrBuilderList();
    /**
     * <code>repeated .TypeValue method_param = 4;</code>
     */
    test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder getMethodParamOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code RequestContext}
   */
  public  static final class RequestContext extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestContext)
      RequestContextOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestContext.newBuilder() to construct.
    private RequestContext(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestContext() {
      clzName_ = "";
      methodName_ = "";
      methodParam_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestContext();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestContext(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              seq_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              clzName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              methodName_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                methodParam_ = new java.util.ArrayList<test.chao.pa.netty.RootProtoGen.TypeValue>();
                mutable_bitField0_ |= 0x00000001;
              }
              methodParam_.add(
                  input.readMessage(test.chao.pa.netty.RootProtoGen.TypeValue.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          methodParam_ = java.util.Collections.unmodifiableList(methodParam_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.chao.pa.netty.RootProtoGen.internal_static_RequestContext_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.chao.pa.netty.RootProtoGen.internal_static_RequestContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.chao.pa.netty.RootProtoGen.RequestContext.class, test.chao.pa.netty.RootProtoGen.RequestContext.Builder.class);
    }

    public static final int SEQ_FIELD_NUMBER = 1;
    private int seq_;
    /**
     * <code>int32 seq = 1;</code>
     */
    public int getSeq() {
      return seq_;
    }

    public static final int CLZ_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object clzName_;
    /**
     * <code>string clz_name = 2;</code>
     */
    public java.lang.String getClzName() {
      java.lang.Object ref = clzName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clzName_ = s;
        return s;
      }
    }
    /**
     * <code>string clz_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClzNameBytes() {
      java.lang.Object ref = clzName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clzName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object methodName_;
    /**
     * <code>string method_name = 3;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>string method_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_PARAM_FIELD_NUMBER = 4;
    private java.util.List<test.chao.pa.netty.RootProtoGen.TypeValue> methodParam_;
    /**
     * <code>repeated .TypeValue method_param = 4;</code>
     */
    public java.util.List<test.chao.pa.netty.RootProtoGen.TypeValue> getMethodParamList() {
      return methodParam_;
    }
    /**
     * <code>repeated .TypeValue method_param = 4;</code>
     */
    public java.util.List<? extends test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder> 
        getMethodParamOrBuilderList() {
      return methodParam_;
    }
    /**
     * <code>repeated .TypeValue method_param = 4;</code>
     */
    public int getMethodParamCount() {
      return methodParam_.size();
    }
    /**
     * <code>repeated .TypeValue method_param = 4;</code>
     */
    public test.chao.pa.netty.RootProtoGen.TypeValue getMethodParam(int index) {
      return methodParam_.get(index);
    }
    /**
     * <code>repeated .TypeValue method_param = 4;</code>
     */
    public test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder getMethodParamOrBuilder(
        int index) {
      return methodParam_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (seq_ != 0) {
        output.writeInt32(1, seq_);
      }
      if (!getClzNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clzName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, methodName_);
      }
      for (int i = 0; i < methodParam_.size(); i++) {
        output.writeMessage(4, methodParam_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (seq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, seq_);
      }
      if (!getClzNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clzName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, methodName_);
      }
      for (int i = 0; i < methodParam_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, methodParam_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.chao.pa.netty.RootProtoGen.RequestContext)) {
        return super.equals(obj);
      }
      test.chao.pa.netty.RootProtoGen.RequestContext other = (test.chao.pa.netty.RootProtoGen.RequestContext) obj;

      if (getSeq()
          != other.getSeq()) return false;
      if (!getClzName()
          .equals(other.getClzName())) return false;
      if (!getMethodName()
          .equals(other.getMethodName())) return false;
      if (!getMethodParamList()
          .equals(other.getMethodParamList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + getSeq();
      hash = (37 * hash) + CLZ_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getClzName().hashCode();
      hash = (37 * hash) + METHOD_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      if (getMethodParamCount() > 0) {
        hash = (37 * hash) + METHOD_PARAM_FIELD_NUMBER;
        hash = (53 * hash) + getMethodParamList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.chao.pa.netty.RootProtoGen.RequestContext parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.chao.pa.netty.RootProtoGen.RequestContext parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.chao.pa.netty.RootProtoGen.RequestContext parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.chao.pa.netty.RootProtoGen.RequestContext parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.chao.pa.netty.RootProtoGen.RequestContext parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.chao.pa.netty.RootProtoGen.RequestContext parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.chao.pa.netty.RootProtoGen.RequestContext parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.chao.pa.netty.RootProtoGen.RequestContext parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.chao.pa.netty.RootProtoGen.RequestContext parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.chao.pa.netty.RootProtoGen.RequestContext parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.chao.pa.netty.RootProtoGen.RequestContext parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.chao.pa.netty.RootProtoGen.RequestContext parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.chao.pa.netty.RootProtoGen.RequestContext prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestContext}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestContext)
        test.chao.pa.netty.RootProtoGen.RequestContextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.chao.pa.netty.RootProtoGen.internal_static_RequestContext_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.chao.pa.netty.RootProtoGen.internal_static_RequestContext_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.chao.pa.netty.RootProtoGen.RequestContext.class, test.chao.pa.netty.RootProtoGen.RequestContext.Builder.class);
      }

      // Construct using test.chao.pa.netty.RootProtoGen.RequestContext.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMethodParamFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        seq_ = 0;

        clzName_ = "";

        methodName_ = "";

        if (methodParamBuilder_ == null) {
          methodParam_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          methodParamBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.chao.pa.netty.RootProtoGen.internal_static_RequestContext_descriptor;
      }

      @java.lang.Override
      public test.chao.pa.netty.RootProtoGen.RequestContext getDefaultInstanceForType() {
        return test.chao.pa.netty.RootProtoGen.RequestContext.getDefaultInstance();
      }

      @java.lang.Override
      public test.chao.pa.netty.RootProtoGen.RequestContext build() {
        test.chao.pa.netty.RootProtoGen.RequestContext result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.chao.pa.netty.RootProtoGen.RequestContext buildPartial() {
        test.chao.pa.netty.RootProtoGen.RequestContext result = new test.chao.pa.netty.RootProtoGen.RequestContext(this);
        int from_bitField0_ = bitField0_;
        result.seq_ = seq_;
        result.clzName_ = clzName_;
        result.methodName_ = methodName_;
        if (methodParamBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            methodParam_ = java.util.Collections.unmodifiableList(methodParam_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.methodParam_ = methodParam_;
        } else {
          result.methodParam_ = methodParamBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.chao.pa.netty.RootProtoGen.RequestContext) {
          return mergeFrom((test.chao.pa.netty.RootProtoGen.RequestContext)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.chao.pa.netty.RootProtoGen.RequestContext other) {
        if (other == test.chao.pa.netty.RootProtoGen.RequestContext.getDefaultInstance()) return this;
        if (other.getSeq() != 0) {
          setSeq(other.getSeq());
        }
        if (!other.getClzName().isEmpty()) {
          clzName_ = other.clzName_;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          onChanged();
        }
        if (methodParamBuilder_ == null) {
          if (!other.methodParam_.isEmpty()) {
            if (methodParam_.isEmpty()) {
              methodParam_ = other.methodParam_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMethodParamIsMutable();
              methodParam_.addAll(other.methodParam_);
            }
            onChanged();
          }
        } else {
          if (!other.methodParam_.isEmpty()) {
            if (methodParamBuilder_.isEmpty()) {
              methodParamBuilder_.dispose();
              methodParamBuilder_ = null;
              methodParam_ = other.methodParam_;
              bitField0_ = (bitField0_ & ~0x00000001);
              methodParamBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMethodParamFieldBuilder() : null;
            } else {
              methodParamBuilder_.addAllMessages(other.methodParam_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.chao.pa.netty.RootProtoGen.RequestContext parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.chao.pa.netty.RootProtoGen.RequestContext) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int seq_ ;
      /**
       * <code>int32 seq = 1;</code>
       */
      public int getSeq() {
        return seq_;
      }
      /**
       * <code>int32 seq = 1;</code>
       */
      public Builder setSeq(int value) {
        
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 seq = 1;</code>
       */
      public Builder clearSeq() {
        
        seq_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object clzName_ = "";
      /**
       * <code>string clz_name = 2;</code>
       */
      public java.lang.String getClzName() {
        java.lang.Object ref = clzName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clzName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string clz_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClzNameBytes() {
        java.lang.Object ref = clzName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clzName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clz_name = 2;</code>
       */
      public Builder setClzName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clzName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clz_name = 2;</code>
       */
      public Builder clearClzName() {
        
        clzName_ = getDefaultInstance().getClzName();
        onChanged();
        return this;
      }
      /**
       * <code>string clz_name = 2;</code>
       */
      public Builder setClzNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clzName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>string method_name = 3;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string method_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method_name = 3;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method_name = 3;</code>
       */
      public Builder clearMethodName() {
        
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>string method_name = 3;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        methodName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<test.chao.pa.netty.RootProtoGen.TypeValue> methodParam_ =
        java.util.Collections.emptyList();
      private void ensureMethodParamIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          methodParam_ = new java.util.ArrayList<test.chao.pa.netty.RootProtoGen.TypeValue>(methodParam_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          test.chao.pa.netty.RootProtoGen.TypeValue, test.chao.pa.netty.RootProtoGen.TypeValue.Builder, test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder> methodParamBuilder_;

      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public java.util.List<test.chao.pa.netty.RootProtoGen.TypeValue> getMethodParamList() {
        if (methodParamBuilder_ == null) {
          return java.util.Collections.unmodifiableList(methodParam_);
        } else {
          return methodParamBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public int getMethodParamCount() {
        if (methodParamBuilder_ == null) {
          return methodParam_.size();
        } else {
          return methodParamBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public test.chao.pa.netty.RootProtoGen.TypeValue getMethodParam(int index) {
        if (methodParamBuilder_ == null) {
          return methodParam_.get(index);
        } else {
          return methodParamBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public Builder setMethodParam(
          int index, test.chao.pa.netty.RootProtoGen.TypeValue value) {
        if (methodParamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMethodParamIsMutable();
          methodParam_.set(index, value);
          onChanged();
        } else {
          methodParamBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public Builder setMethodParam(
          int index, test.chao.pa.netty.RootProtoGen.TypeValue.Builder builderForValue) {
        if (methodParamBuilder_ == null) {
          ensureMethodParamIsMutable();
          methodParam_.set(index, builderForValue.build());
          onChanged();
        } else {
          methodParamBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public Builder addMethodParam(test.chao.pa.netty.RootProtoGen.TypeValue value) {
        if (methodParamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMethodParamIsMutable();
          methodParam_.add(value);
          onChanged();
        } else {
          methodParamBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public Builder addMethodParam(
          int index, test.chao.pa.netty.RootProtoGen.TypeValue value) {
        if (methodParamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMethodParamIsMutable();
          methodParam_.add(index, value);
          onChanged();
        } else {
          methodParamBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public Builder addMethodParam(
          test.chao.pa.netty.RootProtoGen.TypeValue.Builder builderForValue) {
        if (methodParamBuilder_ == null) {
          ensureMethodParamIsMutable();
          methodParam_.add(builderForValue.build());
          onChanged();
        } else {
          methodParamBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public Builder addMethodParam(
          int index, test.chao.pa.netty.RootProtoGen.TypeValue.Builder builderForValue) {
        if (methodParamBuilder_ == null) {
          ensureMethodParamIsMutable();
          methodParam_.add(index, builderForValue.build());
          onChanged();
        } else {
          methodParamBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public Builder addAllMethodParam(
          java.lang.Iterable<? extends test.chao.pa.netty.RootProtoGen.TypeValue> values) {
        if (methodParamBuilder_ == null) {
          ensureMethodParamIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, methodParam_);
          onChanged();
        } else {
          methodParamBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public Builder clearMethodParam() {
        if (methodParamBuilder_ == null) {
          methodParam_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          methodParamBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public Builder removeMethodParam(int index) {
        if (methodParamBuilder_ == null) {
          ensureMethodParamIsMutable();
          methodParam_.remove(index);
          onChanged();
        } else {
          methodParamBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public test.chao.pa.netty.RootProtoGen.TypeValue.Builder getMethodParamBuilder(
          int index) {
        return getMethodParamFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder getMethodParamOrBuilder(
          int index) {
        if (methodParamBuilder_ == null) {
          return methodParam_.get(index);  } else {
          return methodParamBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public java.util.List<? extends test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder> 
           getMethodParamOrBuilderList() {
        if (methodParamBuilder_ != null) {
          return methodParamBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(methodParam_);
        }
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public test.chao.pa.netty.RootProtoGen.TypeValue.Builder addMethodParamBuilder() {
        return getMethodParamFieldBuilder().addBuilder(
            test.chao.pa.netty.RootProtoGen.TypeValue.getDefaultInstance());
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public test.chao.pa.netty.RootProtoGen.TypeValue.Builder addMethodParamBuilder(
          int index) {
        return getMethodParamFieldBuilder().addBuilder(
            index, test.chao.pa.netty.RootProtoGen.TypeValue.getDefaultInstance());
      }
      /**
       * <code>repeated .TypeValue method_param = 4;</code>
       */
      public java.util.List<test.chao.pa.netty.RootProtoGen.TypeValue.Builder> 
           getMethodParamBuilderList() {
        return getMethodParamFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          test.chao.pa.netty.RootProtoGen.TypeValue, test.chao.pa.netty.RootProtoGen.TypeValue.Builder, test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder> 
          getMethodParamFieldBuilder() {
        if (methodParamBuilder_ == null) {
          methodParamBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              test.chao.pa.netty.RootProtoGen.TypeValue, test.chao.pa.netty.RootProtoGen.TypeValue.Builder, test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder>(
                  methodParam_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          methodParam_ = null;
        }
        return methodParamBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestContext)
    }

    // @@protoc_insertion_point(class_scope:RequestContext)
    private static final test.chao.pa.netty.RootProtoGen.RequestContext DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.chao.pa.netty.RootProtoGen.RequestContext();
    }

    public static test.chao.pa.netty.RootProtoGen.RequestContext getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestContext>
        PARSER = new com.google.protobuf.AbstractParser<RequestContext>() {
      @java.lang.Override
      public RequestContext parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestContext(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestContext> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestContext> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.chao.pa.netty.RootProtoGen.RequestContext getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseContextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseContext)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 seq = 1;</code>
     */
    int getSeq();

    /**
     * <code>.TypeValue response_value = 2;</code>
     */
    boolean hasResponseValue();
    /**
     * <code>.TypeValue response_value = 2;</code>
     */
    test.chao.pa.netty.RootProtoGen.TypeValue getResponseValue();
    /**
     * <code>.TypeValue response_value = 2;</code>
     */
    test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder getResponseValueOrBuilder();
  }
  /**
   * Protobuf type {@code ResponseContext}
   */
  public  static final class ResponseContext extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseContext)
      ResponseContextOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseContext.newBuilder() to construct.
    private ResponseContext(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseContext() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResponseContext();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseContext(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              seq_ = input.readInt32();
              break;
            }
            case 18: {
              test.chao.pa.netty.RootProtoGen.TypeValue.Builder subBuilder = null;
              if (responseValue_ != null) {
                subBuilder = responseValue_.toBuilder();
              }
              responseValue_ = input.readMessage(test.chao.pa.netty.RootProtoGen.TypeValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(responseValue_);
                responseValue_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.chao.pa.netty.RootProtoGen.internal_static_ResponseContext_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.chao.pa.netty.RootProtoGen.internal_static_ResponseContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.chao.pa.netty.RootProtoGen.ResponseContext.class, test.chao.pa.netty.RootProtoGen.ResponseContext.Builder.class);
    }

    public static final int SEQ_FIELD_NUMBER = 1;
    private int seq_;
    /**
     * <code>int32 seq = 1;</code>
     */
    public int getSeq() {
      return seq_;
    }

    public static final int RESPONSE_VALUE_FIELD_NUMBER = 2;
    private test.chao.pa.netty.RootProtoGen.TypeValue responseValue_;
    /**
     * <code>.TypeValue response_value = 2;</code>
     */
    public boolean hasResponseValue() {
      return responseValue_ != null;
    }
    /**
     * <code>.TypeValue response_value = 2;</code>
     */
    public test.chao.pa.netty.RootProtoGen.TypeValue getResponseValue() {
      return responseValue_ == null ? test.chao.pa.netty.RootProtoGen.TypeValue.getDefaultInstance() : responseValue_;
    }
    /**
     * <code>.TypeValue response_value = 2;</code>
     */
    public test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder getResponseValueOrBuilder() {
      return getResponseValue();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (seq_ != 0) {
        output.writeInt32(1, seq_);
      }
      if (responseValue_ != null) {
        output.writeMessage(2, getResponseValue());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (seq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, seq_);
      }
      if (responseValue_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getResponseValue());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.chao.pa.netty.RootProtoGen.ResponseContext)) {
        return super.equals(obj);
      }
      test.chao.pa.netty.RootProtoGen.ResponseContext other = (test.chao.pa.netty.RootProtoGen.ResponseContext) obj;

      if (getSeq()
          != other.getSeq()) return false;
      if (hasResponseValue() != other.hasResponseValue()) return false;
      if (hasResponseValue()) {
        if (!getResponseValue()
            .equals(other.getResponseValue())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + getSeq();
      if (hasResponseValue()) {
        hash = (37 * hash) + RESPONSE_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getResponseValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.chao.pa.netty.RootProtoGen.ResponseContext parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.chao.pa.netty.RootProtoGen.ResponseContext parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.chao.pa.netty.RootProtoGen.ResponseContext parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.chao.pa.netty.RootProtoGen.ResponseContext parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.chao.pa.netty.RootProtoGen.ResponseContext parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.chao.pa.netty.RootProtoGen.ResponseContext parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.chao.pa.netty.RootProtoGen.ResponseContext parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.chao.pa.netty.RootProtoGen.ResponseContext parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.chao.pa.netty.RootProtoGen.ResponseContext parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.chao.pa.netty.RootProtoGen.ResponseContext parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.chao.pa.netty.RootProtoGen.ResponseContext parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.chao.pa.netty.RootProtoGen.ResponseContext parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.chao.pa.netty.RootProtoGen.ResponseContext prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseContext}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseContext)
        test.chao.pa.netty.RootProtoGen.ResponseContextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.chao.pa.netty.RootProtoGen.internal_static_ResponseContext_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.chao.pa.netty.RootProtoGen.internal_static_ResponseContext_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.chao.pa.netty.RootProtoGen.ResponseContext.class, test.chao.pa.netty.RootProtoGen.ResponseContext.Builder.class);
      }

      // Construct using test.chao.pa.netty.RootProtoGen.ResponseContext.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        seq_ = 0;

        if (responseValueBuilder_ == null) {
          responseValue_ = null;
        } else {
          responseValue_ = null;
          responseValueBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.chao.pa.netty.RootProtoGen.internal_static_ResponseContext_descriptor;
      }

      @java.lang.Override
      public test.chao.pa.netty.RootProtoGen.ResponseContext getDefaultInstanceForType() {
        return test.chao.pa.netty.RootProtoGen.ResponseContext.getDefaultInstance();
      }

      @java.lang.Override
      public test.chao.pa.netty.RootProtoGen.ResponseContext build() {
        test.chao.pa.netty.RootProtoGen.ResponseContext result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.chao.pa.netty.RootProtoGen.ResponseContext buildPartial() {
        test.chao.pa.netty.RootProtoGen.ResponseContext result = new test.chao.pa.netty.RootProtoGen.ResponseContext(this);
        result.seq_ = seq_;
        if (responseValueBuilder_ == null) {
          result.responseValue_ = responseValue_;
        } else {
          result.responseValue_ = responseValueBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.chao.pa.netty.RootProtoGen.ResponseContext) {
          return mergeFrom((test.chao.pa.netty.RootProtoGen.ResponseContext)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.chao.pa.netty.RootProtoGen.ResponseContext other) {
        if (other == test.chao.pa.netty.RootProtoGen.ResponseContext.getDefaultInstance()) return this;
        if (other.getSeq() != 0) {
          setSeq(other.getSeq());
        }
        if (other.hasResponseValue()) {
          mergeResponseValue(other.getResponseValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.chao.pa.netty.RootProtoGen.ResponseContext parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.chao.pa.netty.RootProtoGen.ResponseContext) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int seq_ ;
      /**
       * <code>int32 seq = 1;</code>
       */
      public int getSeq() {
        return seq_;
      }
      /**
       * <code>int32 seq = 1;</code>
       */
      public Builder setSeq(int value) {
        
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 seq = 1;</code>
       */
      public Builder clearSeq() {
        
        seq_ = 0;
        onChanged();
        return this;
      }

      private test.chao.pa.netty.RootProtoGen.TypeValue responseValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          test.chao.pa.netty.RootProtoGen.TypeValue, test.chao.pa.netty.RootProtoGen.TypeValue.Builder, test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder> responseValueBuilder_;
      /**
       * <code>.TypeValue response_value = 2;</code>
       */
      public boolean hasResponseValue() {
        return responseValueBuilder_ != null || responseValue_ != null;
      }
      /**
       * <code>.TypeValue response_value = 2;</code>
       */
      public test.chao.pa.netty.RootProtoGen.TypeValue getResponseValue() {
        if (responseValueBuilder_ == null) {
          return responseValue_ == null ? test.chao.pa.netty.RootProtoGen.TypeValue.getDefaultInstance() : responseValue_;
        } else {
          return responseValueBuilder_.getMessage();
        }
      }
      /**
       * <code>.TypeValue response_value = 2;</code>
       */
      public Builder setResponseValue(test.chao.pa.netty.RootProtoGen.TypeValue value) {
        if (responseValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          responseValue_ = value;
          onChanged();
        } else {
          responseValueBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TypeValue response_value = 2;</code>
       */
      public Builder setResponseValue(
          test.chao.pa.netty.RootProtoGen.TypeValue.Builder builderForValue) {
        if (responseValueBuilder_ == null) {
          responseValue_ = builderForValue.build();
          onChanged();
        } else {
          responseValueBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TypeValue response_value = 2;</code>
       */
      public Builder mergeResponseValue(test.chao.pa.netty.RootProtoGen.TypeValue value) {
        if (responseValueBuilder_ == null) {
          if (responseValue_ != null) {
            responseValue_ =
              test.chao.pa.netty.RootProtoGen.TypeValue.newBuilder(responseValue_).mergeFrom(value).buildPartial();
          } else {
            responseValue_ = value;
          }
          onChanged();
        } else {
          responseValueBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TypeValue response_value = 2;</code>
       */
      public Builder clearResponseValue() {
        if (responseValueBuilder_ == null) {
          responseValue_ = null;
          onChanged();
        } else {
          responseValue_ = null;
          responseValueBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.TypeValue response_value = 2;</code>
       */
      public test.chao.pa.netty.RootProtoGen.TypeValue.Builder getResponseValueBuilder() {
        
        onChanged();
        return getResponseValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.TypeValue response_value = 2;</code>
       */
      public test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder getResponseValueOrBuilder() {
        if (responseValueBuilder_ != null) {
          return responseValueBuilder_.getMessageOrBuilder();
        } else {
          return responseValue_ == null ?
              test.chao.pa.netty.RootProtoGen.TypeValue.getDefaultInstance() : responseValue_;
        }
      }
      /**
       * <code>.TypeValue response_value = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          test.chao.pa.netty.RootProtoGen.TypeValue, test.chao.pa.netty.RootProtoGen.TypeValue.Builder, test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder> 
          getResponseValueFieldBuilder() {
        if (responseValueBuilder_ == null) {
          responseValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              test.chao.pa.netty.RootProtoGen.TypeValue, test.chao.pa.netty.RootProtoGen.TypeValue.Builder, test.chao.pa.netty.RootProtoGen.TypeValueOrBuilder>(
                  getResponseValue(),
                  getParentForChildren(),
                  isClean());
          responseValue_ = null;
        }
        return responseValueBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseContext)
    }

    // @@protoc_insertion_point(class_scope:ResponseContext)
    private static final test.chao.pa.netty.RootProtoGen.ResponseContext DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.chao.pa.netty.RootProtoGen.ResponseContext();
    }

    public static test.chao.pa.netty.RootProtoGen.ResponseContext getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseContext>
        PARSER = new com.google.protobuf.AbstractParser<ResponseContext>() {
      @java.lang.Override
      public ResponseContext parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseContext(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseContext> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseContext> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.chao.pa.netty.RootProtoGen.ResponseContext getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TypeValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TypeValue_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestContext_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestContext_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseContext_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseContext_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026RpcRquestContext.proto\"(\n\tTypeValue\022\014\n" +
      "\004type\030\001 \001(\t\022\r\n\005value\030\002 \001(\014\"f\n\016RequestCon" +
      "text\022\013\n\003seq\030\001 \001(\005\022\020\n\010clz_name\030\002 \001(\t\022\023\n\013m" +
      "ethod_name\030\003 \001(\t\022 \n\014method_param\030\004 \003(\0132\n" +
      ".TypeValue\"B\n\017ResponseContext\022\013\n\003seq\030\001 \001" +
      "(\005\022\"\n\016response_value\030\002 \001(\0132\n.TypeValueB\"" +
      "\n\022test.chao.pa.nettyB\014RootProtoGenb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TypeValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TypeValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TypeValue_descriptor,
        new java.lang.String[] { "Type", "Value", });
    internal_static_RequestContext_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RequestContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestContext_descriptor,
        new java.lang.String[] { "Seq", "ClzName", "MethodName", "MethodParam", });
    internal_static_ResponseContext_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ResponseContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseContext_descriptor,
        new java.lang.String[] { "Seq", "ResponseValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
